### ISSUE TITLE
doc: typo in repo about url should be 'docs.edgee.cloud'

### ISSUE THREAD

**Issue by mikbry** [edgee-cloud/docs#3]
**Describe the bug**
all in the title

**To Reproduce**
1. Go to ['Repo'](https://github.com/edgee-cloud)
2. Click on 'doc.edgee.cloud'

**Expected behavior**
Url should be docs.edgee.cloud

**Screenshots**
![Capture-edgee-docs](https://github.com/user-attachments/assets/c9607628-feb0-42b9-b91a-e0714db891cd)

**Comment by SachaMorard** [comment]
Hello @mikbry. Thanks for the issue. It's fixed ;)
